'use client';

import { useEffect, useState } from 'react';

export default function AiGreeting() {
  const [greeting, setGreeting] = useState('');
  const [isTyping, setIsTyping] = useState(true);
  const [displayedText, setDisplayedText] = useState('');

  useEffect(() => {
    const hour = new Date().getHours();
    let timeOfDay = 'morning';
    if (hour >= 12 && hour < 17) timeOfDay = 'afternoon';
    else if (hour >= 17 && hour < 21) timeOfDay = 'evening';
    else if (hour >= 21 || hour < 5) timeOfDay = 'night';

    const dayOfWeek = new Date().toLocaleDateString('en-AU', {
      weekday: 'long',
    });

    // Track returning visitors
    const returning = localStorage.getItem('ac-visited') === 'true';
    localStorage.setItem('ac-visited', 'true');

    async function fetchGreeting() {
      try {
        const res = await fetch('/api/greeting', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ timeOfDay, dayOfWeek, hour, returning }),
        });

        if (res.ok) {
          const data = await res.json();
          setGreeting(data.greeting);
        } else {
          setGreeting(getFallback(timeOfDay));
        }
      } catch {
        setGreeting(getFallback(timeOfDay));
      }
    }

    fetchGreeting();
  }, []);

  useEffect(() => {
    if (!greeting) return;

    let index = 0;
    setDisplayedText('');
    setIsTyping(true);

    const interval = setInterval(() => {
      if (index < greeting.length) {
        setDisplayedText(greeting.slice(0, index + 1));
        index++;
      } else {
        setIsTyping(false);
        clearInterval(interval);
      }
    }, 30);

    return () => clearInterval(interval);
  }, [greeting]);

  return (
    <div className="min-h-[3.5rem]">
      <div className="ai-greeting">
        {displayedText || (
          <span style={{ opacity: 0.3 }}>Initialising AI...</span>
        )}
        {isTyping && displayedText && <span className="ai-cursor" />}
      </div>
      {!isTyping && displayedText && (
        <span className="font-mono text-[0.65rem] tracking-[2px] uppercase text-[rgba(255,61,0,0.4)] mt-3 block">
          ● Generated by Claude — live
        </span>
      )}
    </div>
  );
}

function getFallback(timeOfDay: string): string {
  const fallbacks: Record<string, string> = {
    morning:
      'Good morning. Ready to explore what AI can do for your business? We build systems that work while you sleep.',
    afternoon:
      "Good afternoon. Halfway through the day — imagine if AI was handling the repetitive half. Let's talk.",
    evening:
      'Good evening. While most businesses wind down, AI keeps working. Let us show you how.',
    night:
      "Working late? So are the AI systems we build for our clients. They never stop. Let's build yours.",
  };
  return fallbacks[timeOfDay] || fallbacks.morning;
}
