import type { Metadata } from 'next';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
import EmailLink from '@/components/EmailLink';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of service for the Agentic Consciousness website, AI consulting services, and free AI-powered business tools. Payments, liability, and usage policies.',
  alternates: { canonical: 'https://agenticconsciousness.com.au/terms' },
  openGraph: {
    title: 'Terms of Service — Agentic Consciousness',
    description: 'Terms of service for the Agentic Consciousness website, AI consulting services, and free AI-powered business tools. Payments, liability, and usage policies.',
    url: 'https://agenticconsciousness.com.au/terms',
    type: 'website',
    images: [{ url: 'https://agenticconsciousness.com.au/opengraph-image', width: 1200, height: 630 }],
  },
};

export default function TermsPage() {
  return (
    <>
    <Nav />
    <main className="pt-[60px] min-h-screen">
      <article className="py-28 px-10 max-md:px-5 max-sm:py-20">
        <div className="max-w-[720px] mx-auto">
          <div className="font-mono text-[0.7rem] tracking-[3px] uppercase mb-3" style={{ color: 'var(--red-text)' }}>LEGAL</div>
          <h1 className="text-[clamp(1.8rem,4vw,2.5rem)] font-black tracking-tight leading-[1.1] mb-8 text-text-primary">
            Terms of Service
          </h1>
          <div className="text-text-dim text-[0.9rem] font-light leading-[1.8] flex flex-col gap-6">
            <p><strong className="text-text-primary font-bold">Last updated:</strong> March 2026</p>

            <p>By using the Agentic Consciousness website and tools, you agree to these terms.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Services</h2>
            <p>We provide AI consulting services and free AI-powered business tools. The free tools are provided as-is for demonstration and utility purposes. They are not a substitute for professional advice.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">AI tool usage</h2>
            <p>Our AI tools use third-party AI models (Anthropic Claude). Results are AI-generated and may contain errors. You are responsible for verifying any output before acting on it. Do not input sensitive personal information (passwords, financial account numbers, health records) into the tools.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Invoice scanner disclaimer</h2>
            <p>The invoice scanner extracts data and provides classification suggestions. Tax deductibility assessments are indicative only — consult a qualified accountant for tax advice. We are not liable for incorrect classifications.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Quote generator disclaimer</h2>
            <p>Quotes generated by our tool are templates only. Pricing is AI-estimated and may not reflect actual market rates. Always verify pricing before sending to clients.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Rate limits</h2>
            <p>Free tools are rate-limited to prevent abuse. Excessive automated use or scraping is prohibited.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Payments</h2>
            <p>Payments for consulting services are processed via Stripe. All prices are in AUD and exclusive of GST unless stated otherwise. Deposits are non-refundable unless agreed in writing. Full payment terms are outlined in individual proposals.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Intellectual property</h2>
            <p>The website design, content, and tools are owned by Agentic Consciousness Pty Ltd. Output generated by our tools for your use belongs to you. You may not copy, reproduce, or redistribute the tools themselves.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Limitation of liability</h2>
            <p>To the maximum extent permitted by Australian law, Agentic Consciousness is not liable for any indirect, incidental, or consequential damages arising from use of our website or tools.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Governing law</h2>
            <p>These terms are governed by the laws of Australia. Any disputes will be resolved in Australian courts.</p>

            <h2 className="text-[1.1rem] font-black text-text-primary mt-4">Contact</h2>
            <p>Agentic Consciousness Pty Ltd<br />Email: <EmailLink className="no-underline hover:underline" style={{ color: 'var(--red-text)' }} /><br />Australia</p>
          </div>
        </div>
      </article>
    </main>
    <Footer />
    </>
  );
}
